version = 1

test_patterns = ["*/test/*.mjs"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = ["nodejs"]
  style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true
