language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

branches:
  only:
  - master

deploy:
  provider: npm
  email: matthias.fax@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
