language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'

branches:
  only:
  - master

deploy:
  provider: npm
  email: matthias.fax@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
